manifest:
  # defaults:
  #   revision: v0.3
  remotes:
    - name: rockyzhang24
      url-base: https://github.com/rockyzhang24
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: rockyzhang24
      revision: v0.3.1
      import: app/west.yml
  self:
    path: config
